* Thetasigma for Monarch
A version of my WCAG AAA compliant Emacs theme ported to Monarch Launcher for MacOS. [[https://www.monarchlauncher.com/][Monarch Launcher]] is a spotlight/raycast/alfred alternative with some neat functionality.

* Installation
Currently (as of v0.8.39), themes in monarch are stored in ~"~/Library/Application Support/com.monarch.macos/themes/"~. Installation will involve downloading the json file and placing it in that folder. Once the file is correctly placed, you can chose the theme in Monarch by typing ~Monarch Settings~ and scrolling to the themes. 

Two methods for installation are detailed below:

** Download & Copy Paste
You can download the file from github here or this [[https://pastebin.com/7FGuQnrd][pastebin link]] and place the file in the folder above by opening Finder and navigating to it. ~⌘+shift+g~ will open up a dialog for you to quickly navigate there.

** With a terminal
#+begin_src shell
curl -L https://pastebin.com/raw/7FGuQnrd > ~/Library/Application\ Support/com.monarch.macos/themes/thetasigma.json
#+end_src
